import React, { useState, useEffect } from 'react';

const notesByTopic = {
    'Aşk': [
        "Aşk, dünyayı değiştiren ve ruhları birleştiren en güçlü duygudur. Bu ürün sana olan sevgimi anlatsın.",
        "Hayatımdaki en güzel şeysin. Bu not sana kalbimin ne kadar hızlı attığını fısıldıyor.",
        "Gözlerindeki ışıltı, bu üründen daha değerli. Seni çok seviyorum!",
        "Bu çiçekler, sana olan sevgimin zamanla solmayacağını, aksine her geçen gün daha da kök salacağını anlatsın.",
        "Sen benim sonsuz baharımsın. Gözlerindeki yeşillik ve ruhundaki aydınlık hiç eksilmesin.",
        "Her yaprağına bir öpücük sakladım. Kokusu sana ait olduğum yeri hatırlatsın.",
        "Aşkımız, bu çiçekler gibi nadir ve değerli. Her anını sonsuza dek saklayacağım.",
        "Sana bakmak, en güzel çiçeğin açılışını izlemek gibi. Hepsi seninle başladı, hepsi sende duruldu.",
        "Hayatımın en güzel mevsimi, seninle tanıştığım gün başladı. Sen benim güneşimsin, çiçeklerim seninle açıyor.",
        "Bu demet, kalbimin senin için attığı her ritmi temsil ediyor. Sonsuza dek senin.",
        "Seninle geçen her an, ömrümün en özel kokusu. İyi ki yanımdasın, sevgilim.",
        "Aşkın nehrinde yüzüyorum ve kıyısı sensin. Bu çiçekler sana olan akıntımı sembolize ediyor.",
        "Seninle nefes almak, en güzel güle dokunmak gibi. Gözlerin benim cennet bahçem.",
        "Güllerin kırmızısı bile, sana duyduğum tutkunun yanında soluk kalır.",
        "Bu çiçekler, sana ilk görüşte aşık olduğum o anki kalp çarpıntımı taşıyor.",
        "Seninle yanımda olmak, fırtınadan sonra açan en cesur çiçek gibi.",
        "Her an seni düşünmek, en güzel şiiri yazmak gibi. Sen benim ilham kaynağımsın.",
        "Tıpkı bu çiçeklerin su ihtiyacı gibi, benim de sana olan ihtiyacım hiç bitmiyor.",
        "Bu, sana olan derin ve sarsılmaz arzumun kokusunu taşıyan bir demet.",
        "Seninle yeniden doğdum. Bu çiçekler, hayatıma kattığın taze rüzgarın bir esintisi.",
        "Gözlerin, benim pusulam. Gönlümün en ateşli çiçeği, sadece senin için açıyor.",
        "Bu çiçekler, dudaklarıma kilitlediğim ama gözlerimin sana haykırdığı tüm sözler.",
        "Sana dokunuşumda hissettiğim o büyülü an, bu çiçeklerin ışıltısında gizli.",
        "Varlığın, hayatımın en büyük hediyesi. Teşekkür ederim, sevgilim.",
        "Bu demetteki her renk, bana yaşattığın her güzel duyguyu temsil ediyor.",
        "Aşkımız, dikenlerine rağmen açan en saf zambak gibi.",
        "Sen, hayatımın en karmaşık anında bile huzur veren bir kır çiçeğisin.",
        "Bu çiçekler, kalbimdeki iyiliğin ve saflığın seninle büyüdüğünü anlatıyor.",
        "Bana gösterdiğin sabır ve sevgi için minnettarım. Sen benim her şeyimsin.",
        "Seninle birlikteyken her şey daha anlamlı. Hayatımı güzelleştirdiğin için teşekkürler.",
        "Bu çiçekler, sana olan sevgimin ne kadar gerçek ve içten olduğunu gösteriyor.",
        "Gülüşün, tüm dünyayı aydınlatan bir mucize. Seninle olmak, en büyük şansım.",
        "Seninle geçen her gün, cennetten bir köşe. Bu demet, o köşenin kokusu.",
        "Aşkın, kışın ortasında açan bir güneş çiçeği gibi. Hep ışık saçıyorsun.",
        "Bu çiçekler, birlikte kuracağımız neşeli günlerin habercisi olsun.",
        "Sen benim en tatlı kaçamağım, hayatımın en güzel sürprizisin.",
        "Tüm zorluklara rağmen, seninle olmak bana umut veriyor.",
        "Bu çiçekler, kalbimin senin için attığı mutlu dansı görsün.",
        "Gözlerindeki neşe, tüm karanlıkları silen bir ışık. Sen benim yaşam kaynağımsın.",
        "Seninleyken, her gün bir bayram. Bu çiçekler, kutlamamızın simgesi.",
        "Aşkımız, her gün yeniden açan, canlı ve dinamik bir bahçe.",
        "Bu çiçeklerin tazeliği, ilişkimizin her daim genç kalacağını fısıldıyor.",
        "Güneşin doğuşu kadar güzel ve yeni bir başlangıçsın. Seni seviyorum, hayat ışığım.",
        "Bu demet, sana özel seçildi, tıpkı kalbimin seni seçtiği gibi.",
        "Senden gelen her mesaj, bu çiçeklerin kokusu kadar beni sarhoş ediyor.",
        "Seninle paylaştığımız tüm sırlar, tüm gülüşler bu çiçeklerde yaşıyor.",
        "Bu çiçekleri kokla; sana olan sevgimin en samimi halini duyacaksın.",
        "Seninle kurduğumuz dünya, en güzel renklerin birleşimi.",
        "Bu çiçekler, aramızdaki o görünmez ama güçlü bağı temsil ediyor.",
        "Sana her baktığımda, ilk günkü heyecanı yaşıyorum. Aşkım hiç bitmesin.",
        "Hayatımın romanında, en güzel bölümün başlığı sensin.",
        "Bu çiçekler, sana olan düşkünlüğümü sessizce anlatıyor.",
        "Senin yanında tamamen kendim olabiliyorum. İşte bu, gerçek aşk.",
    ],
    'Teşekkür': [
        "Hayatıma kattığın her şey için binlerce teşekkür ederim. Minnettarım.",
        "Zor zamanlarımda yanımda olduğun için bu hediyeyle sana teşekkür etmek istedim. Sen harikasın!",
        "İyi kalbin ve yardımseverliğin için sana bu notu yazıyorum. İyi ki varsın.",
        "Sadece bir çiçek değil, aynı zamanda sana olan minnettarlığımın küçük bir göstergesi.",
        "Desteğin, hayatımdaki en güzel melodidir. Her şey için çok teşekkür ederim.",
        "Gülümsemen, günümü aydınlatıyor. Varlığın için ne kadar şükretsem az.",
        "Bana gösterdiğin anlayış ve sabır için kalpten bir teşekkür.",
        "Senin gibi birine sahip olduğum için kendimi çok şanslı hissediyorum. İyi ki benimlesin.",
        "Her zaman ilk aradığım kişi olduğun için sana kocaman bir teşekkür borçluyum.",
        "Bu çiçekler, bana verdiğin huzurun ve güvenin küçük bir yansıması.",
        "Yaptığın küçücük şeyler bile benim için çok değerli. Tüm inceliğin için teşekkürler.",
        "Hayatıma kattığın o pozitif enerji için ne desem bilemiyorum. Sağ ol!",
        "Gözüm kapalı güvenebildiğim tek insansın. Bu hediyeyi sana bu yüzden yolluyorum.",
        "Senin dostluğun/sevgin benim en büyük gücümdür. Teşekkürler, canım.",
        "Unutulmaz anılar biriktirmemize yardım ettiğin için sana teşekkür etmek istedim.",
        "Sadece olduğun kişi için bile sana binlerce kez minnettarım.",
        "Zorlu bir dönemi senin sayende atlattım. Yardım elin için teşekkür ederim.",
        "Seninle tanışmak, hayatımın dönüm noktası oldu. Şükranla.",
        "Bu çiçeklerin kokusu, bana senin güzel ruhunu hatırlatıyor.",
        "Bana inandığın ve desteklediğin her an için ne kadar teşekkür etsem az.",
        "Senin gibi değerli bir hazineye sahip olmak büyük bir ayrıcalık.",
        "İçtenliğin ve samimiyetin için sana minnet borçluyum.",
        "Küçük bir jest, büyük bir kalp. Tüm yaptıkların için teşekkürler.",
        "Hayatıma neşe kattığın için sana bu neşeli çiçekleri gönderiyorum.",
        "Varlığınla her şeyi güzelleştiriyorsun. Seni takdir ediyorum.",
        "Seninle birlikte olmak, hayatın en büyük hediyesi. Sonsuz teşekkürler.",
        "Her defasında beni şaşırttığın ve mutlu ettiğin için sana minnettarım.",
        "Bu, hayatıma kattığın tüm güzel renklere karşılık küçük bir demet.",
        "Sana verdiğim değeri anlatmaya yetmez ama kabul et lütfen.",
        "Bana rehberlik ettiğin ve yol gösterdiğin için teşekkürler.",
        "Senin gibi eşsiz bir ruha sahip olduğum için gurur duyuyorum.",
        "Sadece yanımda olman bile bana güç veriyor. Çok sağ ol.",
        "Senin o güzel kalbin, dünyayı daha yaşanabilir kılıyor. Teşekkür ederim.",
        "Bu çiçekler, tüm o sessiz fedakârlıkların için.",
        "Hayatımdaki boşluğu dolduran, kıymetli varlığına teşekkürler.",
        "Sen benim sığınağım, en büyük destekçimsin. Bu hediyeyle sana olan saygımı sunuyorum.",
        "Sana duyduğum derin takdiri kelimelerle ifade edemem, o yüzden bu çiçekleri seçtim.",
        "Bana özel hissettirdiğin her an için sana minnettarım.",
        "Bu küçük teşekkür notu, büyük bir içtenlikle yazıldı. İyi ki varsın!",
        "Her zaman en iyimi ortaya çıkarmam için bana ilham verdiğin için teşekkürler.",
        "Bu çiçekler, senin aydınlık kişiliğine adanmıştır. Parlamaya devam et.",
        "Bana güvendiğin ve beni cesaretlendirdiğin her an için teşekkür ederim.",
        "Seninle geçirdiğim her saniye bir armağan. Minnettarım.",
        "Seninle yaşamak/çalışmak bir zevk. Tüm yardımların için teşekkürler.",
        "Bazen bir teşekkür yetmez ama lütfen kalbimin derinliğini hisset.",
        "En zor anımda bile bana ışık oldun. Asla unutmayacağım.",
        "Bu çiçekler, benim için ne kadar özel olduğunu fısıldıyor.",
        "Senin gibi düşünceli bir arkadaş/sevgili/meslektaş olduğu için çok şanslıyım.",
        "Hayatıma getirdiğin tüm o sihirli anlar için sana binlerce kez teşekkürler.",
        "Her şeye rağmen yanımda durduğun için sana en içten dileklerimle teşekkür ederim.",
        "Bu hediyeyi, eşsiz nezaketin ve cömertliğin için kabul et lütfen.",
        "Hayatıma kattığın pozitif etki paha biçilmez. Sonsuz minnetle.",
        "Senin gibi nadide bir çiçeği tanıma şansı bulduğum için şanslıyım.",
    ],
    'Destek': [
        "Her zaman arkanızdayım. Unutmayın, birlikte her zorluğun üstesinden gelebiliriz.",
        "Cesaretinize hayranım! Bu ürün size güç ve motivasyon versin.",
        "Desteğimi her daim hisset. Yapabilirsin!",
        "Bu zorluk geçecek ve sen her zamankinden daha güçlü olacaksın. Sana güveniyorum.",
        "Vazgeçme! Her şey düzelecek ve ben seninleyim, sonuna kadar.",
        "Korkuların seni durdurmasın. Bu çiçekler sana cesaretin kokusunu fısıldasın.",
        "Unutma, sen tek başına değilsin. Omuz omuza, bu engeli aşacağız.",
        "Senin ışığın, her türlü karanlığı yenebilecek güçte. Parlamaya devam et.",
        "Büyük şeyler başarabileceğini biliyorum. Sadece kendine inanmaya devam et.",
        "Bu hediyeyle sana ihtiyacın olan tüm pozitif enerjiyi gönderiyorum.",
        "Yolculuğun ne kadar zor olursa olsun, ben senin en büyük destekçin olacağım.",
        "İnanılmaz bir güce sahipsin. Bu çiçekler, sana bunu hatırlatsın.",
        "Düştüğünde seni kaldıracak ilk kişi benim. Sakın pes etme.",
        "Senin kararlılığın, önündeki her engeli aşmaya yeter. Devam et!",
        "Kalbim ve dualarım seninle. Başarı senin olacak.",
        "Bu sadece geçici bir durum. Yakında her şey daha iyi olacak, söz veriyorum.",
        "Sana verdiğim değeri ve desteği bu çiçeklerle ifade etmek istedim.",
        "Senin gibi azimli birini tanımak bir onur. Yanındayım.",
        "Kendi değerini asla unutma. Sen paha biçilmezsin.",
        "Her fırtınanın ardından güneş açar. Sen de o güneşi göreceksin.",
        "Sana sadece bu hediyeyi değil, tüm pozitif enerjimi de yolluyorum.",
        "Senin cesaret hikayen, birçok kişiye ilham verecek. İlerlemeye devam et.",
        "Bu yolda yalnız yürümediğini bilmen için bu notu yazdım.",
        "Mücadelen takdire şayan. Pes etmek yok, ben arkandayım.",
        "Sana olan inancım tam. Başaracaksın, biliyorum.",
        "Her adımında seninle birlikte yürüyorum. Kendini yalnız hissetme.",
        "Bu çiçekler, sana olan sevgimin ve sarsılmaz desteğimin simgesi.",
        "Başarı sadece bir mesafe uzakta. Adımlarını cesaretle at.",
        "Bazen en güçlü savaşçılar bile dinlenmeye ihtiyaç duyar. İhtiyacın olursa buradayım.",
        "Senin ruhun yenilmezdir. Bu geçici zorluk seni yıldıramaz.",
        "Gözlerindeki o azmi görüyorum. Bırakma, hedefine ulaşacaksın.",
        "Sana sarılamasam da, bu çiçekler seni benim adıma kucaklasın.",
        "Ne kadar harika biri olduğunu unutmuş olabilirsin, ama ben unutmadım.",
        "Senden gelen her haber beni mutlu ediyor. Sana tüm kalbimle destek veriyorum.",
        "Bu çiçekler, senin ruhundaki güzelliği ve gücü temsil ediyor.",
        "Seninle gurur duyuyorum, ne olursa olsun. Desteğim koşulsuz.",
        "Hayat, bazen en güçlü olanı test eder. Sen bu testten başarıyla çıkacaksın.",
        "Kendine karşı nazik ol. Ben sana her zaman destek olmaya hazırım.",
        "Umutsuzluğa kapılma. Her zaman bir çıkış yolu vardır ve onu bulacağız.",
        "Bana ne zaman ihtiyacın olursa, sadece bir telefon uzağındayım.",
        "Senin gibi güçlü ve dirençli birini tanımak ilham verici.",
        "Bu hediyeyle sana biraz huzur ve moral vermek istedim.",
        "Yarın yeni bir gün ve yeni bir şans demek. Bugün pes etme.",
        "Senin yanımda olmak, benim için de büyük bir güç kaynağı.",
        "Unutma, hatalar sadece öğrenme fırsatlarıdır. Yola devam et.",
        "Bu çiçeklerin tazeliği, sana yeni bir başlangıç umudu versin.",
        "Tüm kalbimle sana enerji ve güç yolluyorum. Kabul et.",
        "Geri adım atman gerekirse at, ama asla durma. Ben hep arkanda duracağım.",
        "Senin bu mücadeleyi kazanacağına dair en ufak bir şüphem yok.",
        "Sana olan sevgim ve güvenim sonsuzdur. Yapabilirsin!",
        "Sana bu çiçekleri, içindeki savaşçıyı kutlamak için gönderiyorum.",
        "En zorlu tepeden sonra manzara her zaman daha güzeldir. Az kaldı.",
        "Bu demet, sana 'Ben buradayım!' diye bağırsın.",
    ],
    'Kutlama': [
        "Yeni başlangıçlar kutlu olsun! Başarılarının devamını dilerim.",
        "Büyük günün kutlu olsun! Mutluluğun daim olsun.",
        "Bu özel anı seninle kutlamak harika. Nice güzel yaşlara/başarılara!",
        "Bu muhteşem başarının tadını çıkar! Harikasın, tebrikler!",
        "Kariyerindeki/hayatındaki bu büyük adımı kutlarım. Gurur duyuyorum!",
        "Yeni eviniz/işiniz/yaşamınız size şans ve mutluluk getirsin. Kutlu olsun!",
        "Senin için ne kadar mutlu olduğumu kelimelerle anlatamam. En içten dileklerimle.",
        "Hayallerinin gerçekleştiği bu özel günü kutluyorum! Nice hedeflere.",
        "Bu çiçekler, sana olan hayranlığımı ve neşemi ifade etsin.",
        "Bugün senin günün! Keyfini çıkar, her şeyi hak ediyorsun.",
        "Başarıların daim olsun! Bu zafer senin azminin bir kanıtı.",
        "Yolculuğun boyunca seni izlemek ilham vericiydi. Tebrikler!",
        "Hayatındaki bu yeni dönüm noktası sana bolca güzellik getirsin.",
        "Seninle birlikte bu anı kutlamak, benim için büyük bir zevk. Mutluluklar!",
        "Bu güzel başlangıcın hayatına renk katmasını dilerim.",
        "Yaptığın her şeyin meyvesini almana çok sevindim. Kutluyorum!",
        "Bu çiçekler, sana olan takdirimi ve tebriklerimi taşıyor.",
        "Yeni yaşın sana sağlık, huzur ve çokça neşe getirsin. İyi ki doğdun!",
        "Başarın, azminin ve emeğinin en güzel karşılığı. Bravo!",
        "Hayatın sana sunduğu bu güzelliği sonuna kadar hak ediyorsun. Mutlu ol!",
        "Geleceğin, bu çiçekler kadar parlak ve renkli olsun.",
        "Bu özel günü seninle kutlayamasam da, kalbim seninle.",
        "Aşkınız/ilişkiniz sonsuz olsun! Bu mutlu gününüz kutlu olsun.",
        "Seninle iftihar ediyoruz! Bu başarı bir dönüm noktası.",
        "Başarı serüveninde daha nice zirvelere ulaşman dileğiyle.",
        "Tüm bu güzellikleri hak etmek için ne kadar çalıştığını biliyorum. Tebrikler!",
        "Bu çiçekler, zaferinin coşkusunu yansıtsın.",
        "Seninle tanıştığımız için çok şanslıyım. Mutlu günün kutlu olsun!",
        "Hayatının bu yeni sayfasını açarken yanında olduğumu bil.",
        "Ne kadar zeki ve yetenekli olduğunu bir kez daha kanıtladın. Kutlarım!",
        "Bu unutulmaz anı kutlamak için bu küçük hediyeyi gönderiyorum.",
        "Gözlerindeki o mutluluk ışıltısı hiç sönmesin.",
        "Seninle neşe dolu nice kutlamalara şahit olmak dileğiyle.",
        "Emeğin, sabrın ve inancın kutlu olsun. Tebrikler kahraman!",
        "Birlikte nice güzel anılar biriktireceğimiz bir yıla/döneme.",
        "Hayat, bazen en iyisini sona saklar. İşte senin anın!",
        "Bu çiçekler, sana olan sevincimi ve kutlama ruhumu taşıyor.",
        "Gönlünce bir kutlama diliyorum. Tüm dileklerin gerçek olsun.",
        "Geleceğe güvenle bakmaya devam et. Senin için çok heyecanlıyım.",
        "Bu özel gün, hayatının en güzel anı olsun. Sonsuz mutluluklar.",
        "Senin başarın, bizim de başarımızdır. Hepimizi mutlu ettin!",
        "Bu çiçeklerle sana bol şans ve başarı enerjisi gönderiyorum.",
        "Düğün/mezuniyet/terfi/doğum günün kutlu olsun! Muhteşemsin.",
        "Yaptığın fark için sana bu notla teşekkür etmek istedim.",
        "Bu, sadece bir başlangıç! Daha büyük başarılara doğru ilerle.",
        "Hayatındaki bu olumlu değişim için çok mutluyum.",
        "Tüm yorgunluklarına değdi. Şimdi dinlenme ve kutlama zamanı.",
        "Birlikte kutlayamadığımız için üzgünüm ama kalbim seninle kadeh kaldırıyor.",
        "Senin gibi birinin bu başarıya ulaşmasına şaşırmadım. Tebrikler!",
        "Bu çiçekler, seninle birlikte gelen neşenin bir sembolü.",
        "Yeni maceran kutlu olsun! Her şey gönlünce olsun.",
        "Bu özel günü asla unutma. Tüm başarılarınla gurur duyuyorum.",
        "Senin mutluluğun, benim de mutluluğumdur. İyi ki varsın!",
    ],
};

const Note = ({ selectedTopic, onNoteGenerated }) => {

    useEffect(() => {

        if (selectedTopic) {

            const topicNotes = notesByTopic[selectedTopic];
            
            if (topicNotes && topicNotes.length > 0) {

                const randomIndex = Math.floor(Math.random() * topicNotes.length);
                const generatedNote = topicNotes[randomIndex];
                onNoteGenerated(generatedNote);
                
            } else {

                console.warn(`[Note.jsx] Konu "${selectedTopic}" için kayıtlı not bulunamadı.`);
                onNoteGenerated(`Seçilen konu (${selectedTopic}) için hazır not bulunamadı.`);
            }
        }
    }, [selectedTopic, onNoteGenerated]);

    return null;
};

export default Note;